blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/octo-org/octo-repo/discussions/new?category=q-a
    about: Ask questions and discuss with other community members.
