name = "mietevo-backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[routes]]
pattern = "backend.mietevo.de"
custom_domain = true

[vars]
# API_KEY = "your-secret-key"
# GEMINI_API_KEY = "your-gemini-api-key"
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_KEY = "your-supabase-key"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001" # Unique ID for this limiter
simple = { limit = 10, period = 60 } # 10 requests per 60 seconds
