name = "mietevo-backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[routes]]
pattern = "backend.mietevo.de"
custom_domain = true

[vars]
# API_KEY = "your-secret-key"
# GEMINI_API_KEY = "your-gemini-api-key"
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_KEY = "your-supabase-key"
